name: Deploy database to DEV environment

on:
  push:
    branches: [ "dev" ]
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: azure/sql-action@v2.2
        with:        
          connection-string: '${{ secrets.DEV_DB_CONNECTION_STRING }}'
          path: './WatchIT.Database/WatchIT.Database.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'                 # Optional build options passed to dotnet build
          arguments: '/p:DropObjectsNotInSource=true'
      
