name: Deploy database to DEV environment

on:
  push:
    branches: [ "dev" ]
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Visual Studio Developer Console
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Build project
        run: msbuild ./WatchIT.Database/WatchIT.Database.sqlproj /p:Configuration=Release
      - name: Publish artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Database
          path: ${{ github.workspace }}\bin\Output\
