name: Pull request build

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Build project
        run: msbuild ./WatchIT.Database/WatchIT.Database.sqlproj
