name: Pull request build

on:
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Visual Studio Developer Console
        uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Build project
        run: msbuild ./WatchIT.Database/WatchIT.Database.sqlproj
